__version__ = '6.0.0'
__pyversion__ = '<=3.9.6'
__title__ = 'cso_utils'
__author__ = 'Clothing Shop Online'
__requests__ = 'requests<=2.25.1'
__pygithub__ = 'PyGithub<=1.55'
__pytest__ = 'pytest<=6.2.4'
__pymysql__ = 'PyMySQL<=1.0.2'
__beautifulsoup__ = 'beautifulsoup4<=4.10.0'