__version__ = '3.5.1'
__pyversion__ = '<=3.9.5'
__title__ = 'cso_utils'
__author__ = 'Clothing Shop Online'
__requests__ = 'requests<=2.25.1'
__pygithub__ = 'PyGithub<=1.55'
__pytest__ = 'pytest<=6.2.4'