__version__ = 'development'
__pyversion__ = '<3.9'
__title__ = 'cso_utils'
__author__ = 'Clothing Shop Online'
__requests__ = 'requests<=2.25.1'
__pygithub__ = 'PyGithub<=1.54.1'
__zenpy__ = 'zenpy<=2.0.24'